/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FachIdRouteImport } from './routes/fach.$id'
import { Route as FachIdThemaTopicIdRouteImport } from './routes/fach.$id.thema.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FachIdRoute = FachIdRouteImport.update({
  id: '/fach/$id',
  path: '/fach/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FachIdThemaTopicIdRoute = FachIdThemaTopicIdRouteImport.update({
  id: '/thema/$topicId',
  path: '/thema/$topicId',
  getParentRoute: () => FachIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fach/$id': typeof FachIdRouteWithChildren
  '/fach/$id/thema/$topicId': typeof FachIdThemaTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fach/$id': typeof FachIdRouteWithChildren
  '/fach/$id/thema/$topicId': typeof FachIdThemaTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fach/$id': typeof FachIdRouteWithChildren
  '/fach/$id/thema/$topicId': typeof FachIdThemaTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fach/$id' | '/fach/$id/thema/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fach/$id' | '/fach/$id/thema/$topicId'
  id: '__root__' | '/' | '/fach/$id' | '/fach/$id/thema/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FachIdRoute: typeof FachIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fach/$id': {
      id: '/fach/$id'
      path: '/fach/$id'
      fullPath: '/fach/$id'
      preLoaderRoute: typeof FachIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fach/$id/thema/$topicId': {
      id: '/fach/$id/thema/$topicId'
      path: '/thema/$topicId'
      fullPath: '/fach/$id/thema/$topicId'
      preLoaderRoute: typeof FachIdThemaTopicIdRouteImport
      parentRoute: typeof FachIdRoute
    }
  }
}

interface FachIdRouteChildren {
  FachIdThemaTopicIdRoute: typeof FachIdThemaTopicIdRoute
}

const FachIdRouteChildren: FachIdRouteChildren = {
  FachIdThemaTopicIdRoute: FachIdThemaTopicIdRoute,
}

const FachIdRouteWithChildren =
  FachIdRoute._addFileChildren(FachIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FachIdRoute: FachIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
