/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FachIdRouteImport } from './routes/fach.$id'
import { Route as LernenIdRouteImport } from './routes/lernen.$id'
import { Route as PruefungIdRouteImport } from './routes/pruefung.$id'
import { Route as AdminFachIdIndexRouteImport } from './routes/admin.fach.$id.index'
import { Route as AdminFachIdThemaTopicIdRouteImport } from './routes/admin.fach.$id.thema.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const FachIdRoute = FachIdRouteImport.update({
  id: '/fach/$id',
  path: '/fach/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenIdRoute = LernenIdRouteImport.update({
  id: '/lernen/$id',
  path: '/lernen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungIdRoute = PruefungIdRouteImport.update({
  id: '/pruefung/$id',
  path: '/pruefung/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFachIdIndexRoute = AdminFachIdIndexRouteImport.update({
  id: '/admin/fach/$id/',
  path: '/admin/fach/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFachIdThemaTopicIdRoute = AdminFachIdThemaTopicIdRouteImport.update({
  id: '/admin/fach/$id/thema/$topicId',
  path: '/admin/fach/$id/thema/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fach/$id': typeof FachIdRoute
  '/lernen/$id': typeof LernenIdRoute
  '/pruefung/$id': typeof PruefungIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/fach/$id/': typeof AdminFachIdIndexRoute
  '/admin/fach/$id/thema/$topicId': typeof AdminFachIdThemaTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fach/$id': typeof FachIdRoute
  '/lernen/$id': typeof LernenIdRoute
  '/pruefung/$id': typeof PruefungIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/fach/$id': typeof AdminFachIdIndexRoute
  '/admin/fach/$id/thema/$topicId': typeof AdminFachIdThemaTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fach/$id': typeof FachIdRoute
  '/lernen/$id': typeof LernenIdRoute
  '/pruefung/$id': typeof PruefungIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/fach/$id/': typeof AdminFachIdIndexRoute
  '/admin/fach/$id/thema/$topicId': typeof AdminFachIdThemaTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fach/$id'
    | '/lernen/$id'
    | '/pruefung/$id'
    | '/admin/'
    | '/admin/fach/$id/'
    | '/admin/fach/$id/thema/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fach/$id'
    | '/lernen/$id'
    | '/pruefung/$id'
    | '/admin'
    | '/admin/fach/$id'
    | '/admin/fach/$id/thema/$topicId'
  id:
    | '__root__'
    | '/'
    | '/fach/$id'
    | '/lernen/$id'
    | '/pruefung/$id'
    | '/admin/'
    | '/admin/fach/$id/'
    | '/admin/fach/$id/thema/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FachIdRoute: typeof FachIdRoute
  LernenIdRoute: typeof LernenIdRoute
  PruefungIdRoute: typeof PruefungIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFachIdIndexRoute: typeof AdminFachIdIndexRoute
  AdminFachIdThemaTopicIdRoute: typeof AdminFachIdThemaTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fach/$id': {
      id: '/fach/$id'
      path: '/fach/$id'
      fullPath: '/fach/$id'
      preLoaderRoute: typeof FachIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/$id': {
      id: '/lernen/$id'
      path: '/lernen/$id'
      fullPath: '/lernen/$id'
      preLoaderRoute: typeof LernenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung/$id': {
      id: '/pruefung/$id'
      path: '/pruefung/$id'
      fullPath: '/pruefung/$id'
      preLoaderRoute: typeof PruefungIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fach/$id/': {
      id: '/admin/fach/$id/'
      path: '/admin/fach/$id'
      fullPath: '/admin/fach/$id/'
      preLoaderRoute: typeof AdminFachIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fach/$id/thema/$topicId': {
      id: '/admin/fach/$id/thema/$topicId'
      path: '/admin/fach/$id/thema/$topicId'
      fullPath: '/admin/fach/$id/thema/$topicId'
      preLoaderRoute: typeof AdminFachIdThemaTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FachIdRoute: FachIdRoute,
  LernenIdRoute: LernenIdRoute,
  PruefungIdRoute: PruefungIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFachIdIndexRoute: AdminFachIdIndexRoute,
  AdminFachIdThemaTopicIdRoute: AdminFachIdThemaTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
